import {
  alignContentMapper,
  alignItemsMapper,
  alignSelfMapper
} from "./styles/alignments.ts";
import {
  borderBottomLeftRadiusMapper,
  borderBottomRightRadiusMapper,
  borderRadiusMapper,
  borderTopLeftRadiusMapper,
  borderTopRightRadiusMapper
} from "./styles/borderRadius.ts";
import {
  borderActiveMapper,
  borderBottomActiveMapper,
  borderBottomFocusMapper,
  borderBottomHoverMapper,
  borderBottomMapper,
  borderFocusMapper,
  borderHoverMapper,
  borderLeftActiveMapper,
  borderLeftFocusMapper,
  borderLeftHoverMapper,
  borderLeftMapper,
  borderMapper,
  borderRightActiveMapper,
  borderRightFocusMapper,
  borderRightHoverMapper,
  borderRightMapper,
  borderTopActiveMapper,
  borderTopFocusMapper,
  borderTopHoverMapper,
  borderTopMapper
} from "./styles/borders.ts";
import {
  boxShadowActiveMapper,
  boxShadowFocusMapper,
  boxShadowHoverMapper,
  boxShadowMapper
} from "./styles/boxShadow.ts";
import {
  backgroundColorActiveMapper,
  backgroundColorFocusMapper,
  backgroundColorHoverMapper,
  backgroundColorMapper,
  colorActiveMapper,
  colorFocusMapper,
  colorHoverMapper,
  colorMapper
} from "./styles/colors.ts";
import {
  fillFocusMapper,
  fillHoverMapper,
  fillMapper,
  strokeFocusMapper
} from "./styles/fill.ts";
import {
  fontFamilyMapper,
  fontSizeMapper,
  fontStyleMapper,
  fontWeightMapper
} from "./styles/fonts.ts";
import { columnGapMapper, gapMapper, rowGapMapper } from "./styles/gap.js";
import {
  gridAutoColumnsMapper,
  gridAutoRowsMapper,
  gridTemplateColumnsMapper,
  gridTemplateRowsMapper
} from "./styles/grid.ts";
import {
  justifyContentMapper,
  justifyItemsMapper,
  justifySelfMapper
} from "./styles/justify.ts";
import {
  marginBottomMapper,
  marginLeftMapper,
  marginMapper,
  marginRightMapper,
  marginTopMapper,
  marginXMapper,
  marginYMapper
} from "./styles/margins.ts";
import {
  paddingBottomMapper,
  paddingLeftMapper,
  paddingMapper,
  paddingRightMapper,
  paddingTopMapper,
  paddingXMapper,
  paddingYMapper
} from "./styles/paddings.ts";
import {
  heightMapper,
  lineHeightMapper,
  maxHeightMapper,
  maxWidthMapper,
  minHeightMapper,
  minWidthMapper,
  widthMapper
} from "./styles/sizings.ts";
import type { StyledSystemPropsMapping } from "./types.ts";

export const styledSystemPropsMappings: StyledSystemPropsMapping = {
  width: widthMapper,
  height: heightMapper,
  maxWidth: maxWidthMapper,
  maxHeight: maxHeightMapper,
  minHeight: minHeightMapper,
  minWidth: minWidthMapper,
  lineHeight: lineHeightMapper,
  gap: gapMapper,
  rowGap: rowGapMapper,
  columnGap: columnGapMapper,
  margin: marginMapper,
  marginBottom: marginBottomMapper,
  marginLeft: marginLeftMapper,
  marginRight: marginRightMapper,
  marginTop: marginTopMapper,
  marginX: marginXMapper,
  marginY: marginYMapper,
  padding: paddingMapper,
  paddingBottom: paddingBottomMapper,
  paddingLeft: paddingLeftMapper,
  paddingRight: paddingRightMapper,
  paddingTop: paddingTopMapper,
  paddingX: paddingXMapper,
  paddingY: paddingYMapper,
  alignContent: alignContentMapper,
  alignItems: alignItemsMapper,
  alignSelf: alignSelfMapper,
  border: borderMapper,
  borderBottom: borderBottomMapper,
  borderBottomActive: borderBottomActiveMapper,
  borderBottomFocus: borderBottomFocusMapper,
  borderBottomHover: borderBottomHoverMapper,
  borderBottomLeftRadius: borderBottomLeftRadiusMapper,
  borderBottomRightRadius: borderBottomRightRadiusMapper,
  borderActive: borderActiveMapper,
  borderFocus: borderFocusMapper,
  borderHover: borderHoverMapper,
  borderLeft: borderLeftMapper,
  borderLeftActive: borderLeftActiveMapper,
  borderLeftFocus: borderLeftFocusMapper,
  borderLeftHover: borderLeftHoverMapper,
  borderRadius: borderRadiusMapper,
  borderRight: borderRightMapper,
  borderRightActive: borderRightActiveMapper,
  borderRightFocus: borderRightFocusMapper,
  borderRightHover: borderRightHoverMapper,
  borderTop: borderTopMapper,
  borderTopActive: borderTopActiveMapper,
  borderTopFocus: borderTopFocusMapper,
  borderTopHover: borderTopHoverMapper,
  borderTopLeftRadius: borderTopLeftRadiusMapper,
  borderTopRightRadius: borderTopRightRadiusMapper,
  color: colorMapper,
  colorActive: colorActiveMapper,
  colorFocus: colorFocusMapper,
  colorHover: colorHoverMapper,
  backgroundColor: backgroundColorMapper,
  backgroundColorActive: backgroundColorActiveMapper,
  backgroundColorFocus: backgroundColorFocusMapper,
  backgroundColorHover: backgroundColorHoverMapper,
  gridAutoColumns: gridAutoColumnsMapper,
  gridAutoRows: gridAutoRowsMapper,
  gridTemplateColumns: gridTemplateColumnsMapper,
  gridTemplateRows: gridTemplateRowsMapper,
  justifyContent: justifyContentMapper,
  justifyItems: justifyItemsMapper,
  justifySelf: justifySelfMapper,
  fontFamily: fontFamilyMapper,
  fontSize: fontSizeMapper,
  fontStyle: fontStyleMapper,
  fontWeight: fontWeightMapper,
  boxShadow: boxShadowMapper,
  boxShadowActive: boxShadowActiveMapper,
  boxShadowFocus: boxShadowFocusMapper,
  boxShadowHover: boxShadowHoverMapper,
  fill: fillMapper,
  fillFocus: fillFocusMapper,
  fillHover: fillHoverMapper,
  stroke: strokeFocusMapper,
  grid: "grid",
  gridArea: "gridArea",
  gridAutoFlow: "gridAutoFlow",
  gridColumn: "gridColumn",
  gridColumnEnd: "gridColumnEnd",
  gridColumnSpan: "gridColumnSpan",
  gridColumnStart: "gridColumnStart",
  gridRow: "gridRow",
  gridRowEnd: "gridRowEnd",
  gridRowSpan: "gridRowSpan",
  gridRowStart: "gridRowStart",
  gridTemplate: "gridTemplate",
  gridTemplateAreas: "gridTemplateAreas",
  overflow: "overflow",
  overflowX: "overflowX",
  overflowY: "overflowY",
  textOverflow: "textOverflow",
  flex: "flex",
  flexBasis: "flexBasis",
  flexDirection: "flexDirection",
  flexFlow: "flexFlow",
  flexGrow: "flexGrow",
  flexShrink: "flexShrink",
  flexWrap: "flexWrap",
  whiteSpace: "whiteSpace",
  letterSpacing: "letterSpacing",
  left: "left",
  right: "right",
  top: "top",
  bottom: "bottom",
  display: "display",
  aspectRatio: "aspectRatio",
  backgroundImage: "backgroundImage",
  backgroundPosition: "backgroundPosition",
  backgroundRepeat: "backgroundRepeat",
  backgroundSize: "backgroundSize",
  content: "content",
  contentVisibility: "contentVisibility",
  cursor: "cursor",
  cursorHover: "cursorHover",
  filter: "filter",
  objectFit: "objectFit",
  objectPosition: "objectPosition",
  opacity: "opacity",
  opacityActive: "opacityActive",
  opacityFocus: "opacityFocus",
  opacityHover: "opacityHover",
  order: "order",
  outline: "outline",
  outlineFocus: "outlineFocus",
  pointerEvents: "pointerEvents",
  position: "position",
  resize: "resize",
  textAlign: "textAlign",
  textDecoration: "textDecoration",
  textTransform: "textTransform",
  transform: "transform",
  transformOrigin: "transformOrigin",
  transformStyle: "transformStyle",
  verticalAlign: "verticalAlign",
  visibility: "visibility",
  willChange: "willChange",
  wordBreak: "wordBreak",
  zIndex: "zIndex"
};
